name: otk_wms_mock
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  audioplayers: ^5.2.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/asn-qr.png
    - assets/images/asn-qr2.png
    - assets/images/hanso-qr.png
    - assets/images/kakuno.png
    - assets/images/location-code.png
    - assets/images/map1.png
    - assets/images/map2.png
    - assets/images/map3.png
    - assets/images/map4.png
    - assets/images/map5.png
    - assets/images/map6.png
    - assets/images/map7.png
    - assets/images/map8.png
    - assets/images/map9.png
    - assets/images/hakodume1.png
    - assets/images/hakodume2.png
    - assets/images/hakodume3.png
    - assets/images/hakodume4.png
    - assets/images/tumituke.png
    - assets/images/tumituke2.png
    - assets/images/tana-location.png
    - assets/images/syohin.jpg
    - assets/images/syohin2.png
    - assets/images/fake-camera.png
    - assets/images/hozyu-label.png
    - assets/images/camera-1.png
    - assets/images/camera-2.png
    - assets/images/camera-3.png
    - assets/images/camera-4.png
    - assets/sounds/hanso-asn.ogg
    - assets/sounds/kakuno-asn.ogg
    - assets/sounds/hanso.ogg
    - assets/sounds/kakuno.ogg
    - assets/sounds/hanso-kanryo.ogg
    - assets/sounds/kakuno-kanryo.ogg
    - assets/sounds/asn-scan.ogg
    - assets/sounds/ng-null.ogg
    - assets/sounds/ng-label.ogg
    - assets/sounds/pi.ogg
    - assets/sounds/pic-start.ogg
    - assets/sounds/pic-start2.ogg
    - assets/sounds/pic-start3.ogg
    - assets/sounds/pic-start4.ogg
    - assets/sounds/pic-start5.ogg
    - assets/sounds/pic-start6.ogg
    - assets/sounds/pic-start7.ogg
    - assets/sounds/pic-next.ogg
    - assets/sounds/pic-syohin.ogg
    - assets/sounds/pic-kanryo.ogg
    - assets/sounds/pic-sentaku.ogg
    - assets/sounds/tumituke.ogg
    - assets/sounds/pl-himoduke.ogg
    - assets/sounds/4.ogg
    - assets/sounds/6.ogg
    - assets/sounds/5.ogg
    - assets/sounds/2.ogg
    - assets/sounds/4c.ogg
    - assets/sounds/8c.ogg
    - assets/sounds/label-harituke.ogg
    - assets/sounds/pic-next-pcs.ogg
    - assets/sounds/pic-next-pcs2.ogg
    - assets/sounds/pic-kanpare.ogg
    - assets/sounds/pic-kanpare2.ogg
    - assets/sounds/kenpin-start.ogg
    - assets/sounds/kenpin-kakunin.ogg
    - assets/sounds/kenpin-kanryo.ogg
    - assets/sounds/rotto.ogg
    - assets/sounds/denpyo.ogg
    - assets/sounds/zensu.ogg
    - assets/sounds/satuei.ogg
    - assets/sounds/shiwake-moto.ogg
    - assets/sounds/shiwake-saki.ogg
    - assets/sounds/shiwake-saki2.ogg
    - assets/sounds/shiwake-kanryo.ogg
    - assets/sounds/shiwake-zenpin.ogg
    - assets/sounds/suryo.ogg
    - assets/sounds/suryo2.ogg
    - assets/sounds/kinkyu-hozyu.ogg
    - assets/sounds/syohin-scan.ogg
    - assets/sounds/hozyu-kanryo.ogg
    - assets/sounds/hozyu-kara.ogg
    - assets/sounds/hozyu-label.ogg
    - assets/sounds/error.ogg
    - assets/sounds/pic-loc1.ogg
    - assets/sounds/pic-loc2.ogg
    - assets/sounds/pic-loc3.ogg
    - assets/sounds/pic-loc.ogg
    - assets/sounds/aki-loc.ogg
    - assets/sounds/ido-kanryo.ogg
    - assets/sounds/kara-pl.ogg
    - assets/sounds/syohin-zensu.ogg
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding asssets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpeg"